### PR TITLE
[PRC] Several small changes

### PR DESCRIPTION
**Pull request by JJ**
None critical, and in fact none to code except for adding requirements.

### CODE REVIEW

**Comment by bricas** [comment]
Thanks for the PR!

This looks pretty good, except these two things:

1. I don't think we want to "fix" #8 -- autogenerated files should not be in the repo
2. The build badge links to your account and not this repo.

I would be happy to merge this once those two things are addressed.

**Comment by bricas** [comment]
Sorry to nitpick, only 1 of the "JJ" items in the build status line was changed -- still one left.

**Comment by JJ** [comment]
I actually changed the badge to point to @edsu's repos, but I can remove that too, no problem.

**Comment by bricas** [comment]
what? why are we removing the badge? 

To clarify, before you removed it completely, you had:

`[Build Status](https://travis-ci.org/edsu/www-wikipedia)`

I would have expected it to be:

`[Build Status](https://travis-ci.org/edsu/www-wikipedia)`

**Comment by JJ** [comment]
Ah, OK. Sorry.

**Pull request merged**
